### ISSUE TITLE
ExtractFromDirectory app throws errors

### ISSUE THREAD

**Issue by adarshp** [clulab/eidos#206]
Hi,

I tried extracting events from the MITRE evaluation document corpus with the following invocation:

```bash
sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ~/ml4ai/WorldModelers/MITRE_Evaluation_Documents output_dir"
```

and things seem to run ok for a while, but then I get this error:

```
17:29:52.902 [run-main-0] INFO  org.clulab.wm.eidos.EidosSystem$ - domainOntologyPath: /org/clulab/wm/eidos/toy_ontology.yml
[error] (run-main-0) java.lang.NullPointerException
java.lang.NullPointerException
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.delayedEndpoint$org$clulab$wm$eidos$apps$ExtractFromDirectory$1(ExtractFromDirectory.scala:22)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$delayedInit$body.apply(ExtractFromDirectory.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.App$$Lambda$5/1422905801.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.main(ExtractFromDirectory.scala:14)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory.main(ExtractFromDirectory.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
[trace] Stack trace suppressed: run last core/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last core/compile:runMain for the full output.
[error] (core/compile:runMain) Nonzero exit code: 1
[error] Total time: 3 s, completed Mar 21, 2018 5:29:52 PM
```

1. Do I have the right invocation?
2. Has anybody else run into this issue?

**Comment by adarshp** [comment]
Nevermind, I got it to work, apparently I needed to have the full path to the input directory in the invocation - the tilde (~) will not work.

**Comment by kwalcock** [comment]
Does it happen to work without the quotes?  The shell might substitute the value in.

**Comment by adarshp** [comment]
Nope, it does not work without the quotes…

--
Adarsh Pyarelal
Postdoctoral Research Associate
School of Information 
& Department of Computer Science
University of Arizona
Office: Harvill 454
http://adarsh.cc

**Comment by kwalcock** [comment]
A relative path should work, as in your output_dir.  I am submitting a PR which should avoid the NullPointerException in favor of a FileNotFoundException.  I'll put your name on it :-)

**Comment by adarshp** [comment]
Thanks Keith!
