### ISSUE TITLE
Eidos throws exceptions on files in our larger collection

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#345]
Documents 10, 11, 17, 25,  26, 28, 30, 31, 42 cause java.util.NoSuchElementException or java.lang.RuntimeException: what? that need to be looked into.

```
Could not process 26_South_Sudan_2018_Humanitarian_Needs_Overview.txt
java.util.NoSuchElementException: key not found: cause
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:97)
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:95)
        at org.clulab.wm.eidos.EidosActions.$anonfun$createEventChain$7(EidosActions.scala:72)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.clulab.wm.eidos.EidosActions.$anonfun$createEventChain$5(EidosActions.scala:69)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.immutable.List.flatMap(List.scala:352)
        at org.clulab.wm.eidos.EidosActions.createEventChain(EidosActions.scala:67)
```

```
Could not process 25_2016_HNO_South Sudan.txt
java.lang.RuntimeException: what?
        at scala.sys.package$.error(package.scala:27)
        at org.clulab.wm.eidos.EidosActions.expandIfNotAvoid(EidosActions.scala:534)
        at org.clulab.wm.eidos.EidosActions.$anonfun$expandArguments$7(EidosActions.scala:495)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.clulab.wm.eidos.EidosActions.$anonfun$expandArguments$6(EidosActions.scala:495)
        at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
        at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
        at org.clulab.wm.eidos.EidosActions.$anonfun$expandArguments$4(EidosActions.scala:494)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.clulab.wm.eidos.EidosActions.expandArguments(EidosActions.scala:484)

**Comment by bsharpataz** [comment]
I think this was fixed with #347
