### ISSUE TITLE
Error accessing norms from grammars

### ISSUE THREAD

**Issue by EgoLaparra** [clulab/eidos#362]
I'm trying to create a rule for temporal attachment using norms:
```
  - name: timeattachment1
    priority: ${ rulepriority }
    label: ${ label }
    action: ${ action }
    pattern: |
      trigger = [norm="B-TMP"]
      theme: Entity = </^nmod/ >nmod_in
```
I've been able to create the attachment with other fields like "lemma", but with "norm" I get this error:
```
Caused by: org.clulab.odin.impl.OdinNamedCompileException: Error parsing rule 'timeattachement1': unrecognized token field
	at org.clulab.odin.impl.RuleReader.mkExtractor(RuleReader.scala:310)
	at org.clulab.odin.impl.RuleReader.$anonfun$mkExtractors$4(RuleReader.scala:85)
	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
	at scala.collection.generic.Growable.loop$1(Growable.scala:54)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:658)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:635)
```
I have also tried with version 7.4.0 of processors, but I get the same outcome. How should I access norms?

**Comment by marcovzla** [comment]
I believe this was added to processors 7.4.1 but it hasn't been released yet.
@MihaiSurdeanu should that version be released soon? or are we waiting for something?

**Comment by kwalcock** [comment]
Thanks, @marcovzla.

**Comment by MihaiSurdeanu** [comment]
@EgoLaparra: can you please try this with publishLocal in processors, first?
If it works, I will release it next.

**Comment by EgoLaparra** [comment]
@MihaiSurdeanu, it works!

**Comment by MihaiSurdeanu** [comment]
Ok, 7.4.1 is being released now. Should be on maven in 5-6 hours.

**Comment by bsharpataz** [comment]
@EgoLaparra  is this resolved?
