### ISSUE TITLE
a question about combining fragment merging with the normalizeGroup action

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/eidos#615]
@MihaiSurdeanu,

I have merged the linkingMigrations branch into migration_schema-zupon. Here's a question:

To preserve the event attachments that come from the normalizeGroup action that you wrote, I need to combine the attachments from both events being merged (bc either can have attachments) like here (the last argument):

https://github.com/clulab/eidos/blob/9be09bf4ad5edc2fe2f602b464d88d75ed17bb9b/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L480

This also means that copyWithNewArgs needs to be given not one, but both events that are being merged (orig and orig2, with the orig2 there only to get its attachments in case it has any):

https://github.com/clulab/eidos/blob/9be09bf4ad5edc2fe2f602b464d88d75ed17bb9b/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L452

But that means I have to pass a second mention/event whenever I use copyWithNewArgs even where it does not make sense, e.g., here:

https://github.com/clulab/eidos/blob/9be09bf4ad5edc2fe2f602b464d88d75ed17bb9b/src/main/scala/org/clulab/wm/eidos/actions/MigrationUtils.scala#L130

Is there a more elegant way to do that? I have tried to have the second event as an option, but that didn't seem to work. 

One other option is to have normalizeGroup attach the group information to the group argument and not to the whole event (that could also help with choosing the more specific argument in our fragment merging action). Let me know what you think. Thanks!

**Comment by maxaalexeeva** [comment]
Note: the code works the way it is now, but it does not look too good with the unnecessary argument passing.

**Comment by BeckySharp** [comment]
@maxaalexeeva, my 2 cents :)
 
1. if you want, you can pass the _attachments_ of the 2nd mention as an Option[Set[Attachment]] and when combining you can do something like `optionalAttachments.getOrElse(Set.empty())` (or something similarish)
2. you could alternatively receive the new mention and add the attachments afterwards (we have a helper method for that)
3. but fwiw the last thing you mentioned seems to be more consistent with what you've done with the other args/attachments, and consistency is often valuable
4. if you choose to pass the Mention, you can use something similar to the code in (1), pass an Option[Mention] and then have something like:
> `val additionalAttachments = optionalMention.map(_.attachments).getOrElse(Set.empty())`

then you should be able to add it below

**Comment by maxaalexeeva** [comment]
Thanks for the feedback, @BeckySharp! Those are all great suggestions!

**Comment by MihaiSurdeanu** [comment]
I agree with Becky.

**Comment by maxaalexeeva** [comment]
Great! I'll try the more consistent version first (Becky's point 3, attaching to arg and not the whole event) and see how that goes.

**Comment by maxaalexeeva** [comment]
Hi @BeckySharp, I might have to take you up on your offer to help (I don't mean for you to be looking at this on the day off tomorrow, but decided to add this here while I still remember what needs to be posted). I am trying to attach ...er...attachments to the relevant argument ("group") instead of the whole event and then to make a copy of the event but with the newly-created argument. Here's where the relevant code starts:

https://github.com/clulab/eidos/blob/c4d57fcdd821f060f4cd8dd719b9dfa2b04ad260/src/main/scala/org/clulab/wm/eidos/EidosActions.scala#L158

And this is the error I am getting:

```
[error] application - 

! @7cd0am2dj - Internal server error, for (GET) [/parseText?text=400+people+left+France+for+Romania.+300+refugees+fled+South+Sudan.+Their+destination+is+Ethiopia.&cagRelevantOnly=false] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchElementException: key not found: org.clulab.odin.TextBoundMention@f48b2ffc]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: java.util.NoSuchElementException: key not found: org.clulab.odin.TextBoundMention@f48b2ffc
        at scala.collection.immutable.Map$Map1.apply(Map.scala:108)
        at org.clulab.wm.eidos.expansion.ArgumentExpander.$anonfun$copyWithNewArgs$5(ArgumentExpander.scala:164)
        at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
        at scala.collection.immutable.Map$Map3.foreach(Map.scala:176)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
        at org.clulab.wm.eidos.expansion.ArgumentExpander.copyWithNewArgs(ArgumentExpander.scala:163)
        at org.clulab.wm.eidos.expansion.ArgumentExpander.expandArgs(ArgumentExpander.scala:105)
        at org.clulab.wm.eidos.expansion.ArgumentExpander.$anonfun$expandArguments$1(ArgumentExpander.scala:33)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.Iterator.foreach(Iterator.scala:929)

```
Do you see anything obviously wrong that I am doing? 

The code runs through with this line (the original code that attaches the attachments to the event):
https://github.com/clulab/eidos/blob/c4d57fcdd821f060f4cd8dd719b9dfa2b04ad260/src/main/scala/org/clulab/wm/eidos/EidosActions.scala#L157

**Comment by maxaalexeeva** [comment]
@BeckySharp helped me fix this! Thanks again!
