### ISSUE TITLE
Timenorm crashes

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#662]
On the kwalcock-EidosTokenizer2 branch, which will soon be merged into master, the attached file takes a very, very long time to process and then finally crashes with the stack trace below.  I'm running the `ExtractFromDirectory` app with program arguments `../corpora/DocDart/txt ../corpora/DocDart/jsonld`.  The same thing seems to happen with or without DCT.  The other problem files *seem* to only have problems with a DCT.  Can a "time person" check it out?

[63d8dfc516fb3ee1c9617667c705e43d.txt](https://github.com/clulab/eidos/files/3580443/63d8dfc516fb3ee1c9617667c705e43d.txt)

```java
Exception in thread "main" java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
	at java.time.temporal.ValueRange.checkValidIntValue(ValueRange.java:330)
	at java.time.temporal.ChronoField.checkValidIntValue(ChronoField.java:722)
	at java.time.LocalDate.plusYears(LocalDate.java:1277)
	at java.time.LocalDate.plus(LocalDate.java:1241)
	at java.time.LocalDateTime.plus(LocalDateTime.java:1194)
	at org.clulab.timenorm.scate.IntersectionRI.$anonfun$following$8(Types.scala:860)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:161)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
	at scala.collection.TraversableOnce$FlattenOps$$anon$1.hasNext(TraversableOnce.scala:464)
	at scala.collection.Iterator$$anon$15.hasNext(Iterator.scala:636)
	at scala.collection.Iterator.toStream(Iterator.scala:1403)
	at scala.collection.Iterator.toStream$(Iterator.scala:1402)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1417)
	at scala.collection.TraversableOnce.toSeq(TraversableOnce.scala:298)
	at scala.collection.TraversableOnce.toSeq$(TraversableOnce.scala:298)
	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1417)
	at org.clulab.timenorm.scate.This.intervals(Types.scala:324)
	at org.clulab.timenorm.scate.This.intervals$(Types.scala:314)
	at org.clulab.timenorm.scate.ThisRI.intervals$lzycompute(Types.scala:337)
	at org.clulab.timenorm.scate.ThisRI.intervals(Types.scala:337)
	at org.clulab.timenorm.scate.This.isDefined(Types.scala:326)
	at org.clulab.timenorm.scate.This.isDefined$(Types.scala:326)
	at org.clulab.timenorm.scate.ThisRI.isDefined$lzycompute(Types.scala:337)
	at org.clulab.timenorm.scate.ThisRI.isDefined(Types.scala:337)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$17(TimeNormFinder.scala:207)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$16(TimeNormFinder.scala:183)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$16$adapted(TimeNormFinder.scala:182)
	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
	at org.clulab.wm.eidos.context.TimeNormFinder.find(TimeNormFinder.scala:182)
	at org.clulab.wm.eidos.EidosSystem.$anonfun$extractFrom$1(EidosSystem.scala:63)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at org.clulab.wm.eidos.EidosSystem.extractFrom(EidosSystem.scala:62)
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:97)
	at org.clulab.wm.eidos.EidosSystem.extractFromText(EidosSystem.scala:135)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2(ExtractFromDirectory.scala:28)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2$adapted(ExtractFromDirectory.scala:24)
	at org.clulab.wm.eidos.utils.Closer$.liftedTree1$1(Closer.scala:20)
	at org.clulab.wm.eidos.utils.Closer$.autoClose(Closer.scala:19)
	at org.clulab.wm.eidos.utils.Closer$AutoCloser.autoClose(Closer.scala:60)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1(ExtractFromDirectory.scala:24)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1$adapted(ExtractFromDirectory.scala:21)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Disconnected from the target VM, address: '127.0.0.1:63907', transport: 'socket'

Process finished with exit code 1
```

**Comment by EgoLaparra** [comment]
Do you have the same problem in other branches?

**Comment by kwalcock** [comment]
I haven't tried it in other branches except one even more complicated where it first appeared.  This branch has a new ParagraphSplitter which does fool with some tokens.  Testing in master would be useful, but it not happening there wouldn't be super informative.  I may get to that shortly.

**Comment by bethard** [comment]
@EgoLaparra: this is most likely to happen when the model gets an impossible date, e.g., February the 31st. In such cases, it will search back or forward in time to find such a date, but of course there is not such date. If you can figure out what date is triggering this, we can see about putting extra guards in for that kind of thing. We already do this for some cases, e.g.
https://github.com/clulab/timenorm/blob/master/src/main/scala/org/clulab/timenorm/scate/Types.scala#L771

**Comment by EgoLaparra** [comment]
@bethard the problem was caused by a "31 April 2018".

**Comment by kwalcock** [comment]
Let it be known that I laughed today!

**Comment by EgoLaparra** [comment]
I thought it could have been an error in the text extraction but they actually wrote it in the original document (2nd page, top right corner): 🤦‍♂ 
https://reliefweb.int/sites/reliefweb.int/files/resources/UNHCR_Ethiopia_April_2018.pdf

**Comment by kwalcock** [comment]
That sounds like good detective work.  An extra exception handler somewhere might take care of the crash.  I hope that the 30 minute wait before the crash can be addressed.  The program may be caught up in a synchronized piece of code or maybe it's somehow just in too tight a loop to effectively switch threads, but what happens is that processor utilization goes way, way down, pretty much to 1.  In the meantime the supercomputer acts like it has a single processor and next to no other documents are completed so that getting 1000 finished in a reasonable time becomes unlikely.  If I hope hard enough, will it be possible?

**Comment by bethard** [comment]
@EgoLaparra: You probably want to add something like the following to the end of `test("IntersectionRI")` in `TypesTest` and then see what we can do to get it to pass.
```scala
    // RI: April 31st
    intercept[java.time.DateTimeException] {
      IntersectionRI(Set(
        RepeatingField(ChronoField.MONTH_OF_YEAR, 4),
        RepeatingField(ChronoField.DAY_OF_MONTH, 31)
      ))
      fail("April 31st should throw an exception")
    }
```
We should probably open a separate issue for this in the timenorm repository.
