### ISSUE TITLE
Timenorm crashes 2

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#663]
This crash occurs with the text file below, but only if there is a DCT present.  That comes from metadata, so no app in the main branch will readily show it.  I've modified branch kwalcock-EidosTokenizer2Crash to produce the error.  It matches what is seen in the more complicated branch.  I hope that narrows it down some.

[713d49b4131b8dd38cc6ae3f92e6307c.txt](https://github.com/clulab/eidos/files/3580680/713d49b4131b8dd38cc6ae3f92e6307c.txt)

```java
Exception in thread "main" java.lang.UnsupportedOperationException: one of List(SimpleInterval(+44100-01-01T00:00,+44200-01-01T00:00), SimpleInterval(+44200-01-01T00:00,+44300-01-01T00:00), SimpleInterval(+44300-01-01T00:00,+44400-01-01T00:00), SimpleInterval(+44400-01-01T00:00,+44500-01-01T00:00), SimpleInterval(+44500-01-01T00:00,+44600-01-01T00:00), SimpleInterval(+44600-01-01T00:00,+44700-01-01T00:00), SimpleInterval(+44700-01-01T00:00,+44800-01-01T00:00), SimpleInterval(+44800-01-01T00:00,+44900-01-01T00:00), SimpleInterval(+44900-01-01T00:00,+45000-01-01T00:00), SimpleInterval(+45000-01-01T00:00,+45100-01-01T00:00), SimpleInterval(+45100-01-01T00:00,+45200-01-01T00:00), SimpleInterval(+45200-01-01T00:00,+45300-01-01T00:00), SimpleInterval(+45300-01-01T00:00,+45400-01-01T00:00), SimpleInterval(+45400-01-01T00:00,+45500-01-01T00:00), SimpleInterval(+45500-01-01T00:00,+45600-01-01T00:00), SimpleInterval(+45600-01-01T00:00,+45700-01-01T00:00), SimpleInterval(+45700-01-01T00:00,+45800-01-01T00:00), SimpleInterval(+45800-01-01T00:00,+45900-01-01T00:00), SimpleInterval(+45900-01-01T00:00,+46000-01-01T00:00), SimpleInterval(+46000-01-01T00:00,+46100-01-01T00:00), SimpleInterval(+46100-01-01T00:00,+46200-01-01T00:00)) is outside of SimpleInterval(2019-06-05T00:00,2019-06-06T00:00)
	at org.clulab.timenorm.scate.NthRIs.intervals$lzycompute(Types.scala:652)
	at org.clulab.timenorm.scate.NthRIs.intervals(Types.scala:650)
	at org.clulab.timenorm.scate.Intervals.iterator(Types.scala:176)
	at org.clulab.timenorm.scate.Intervals.iterator$(Types.scala:176)
	at org.clulab.timenorm.scate.NthRIs.iterator(Types.scala:645)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$17(TimeNormFinder.scala:210)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$16(TimeNormFinder.scala:183)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$16$adapted(TimeNormFinder.scala:182)
	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
	at org.clulab.wm.eidos.context.TimeNormFinder.find(TimeNormFinder.scala:182)
	at org.clulab.wm.eidos.EidosSystem.$anonfun$extractFrom$1(EidosSystem.scala:64)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at org.clulab.wm.eidos.EidosSystem.extractFrom(EidosSystem.scala:63)
	at org.clulab.wm.eidos.EidosSystem.extractFromDocWithDct(EidosSystem.scala:143)
	at org.clulab.wm.eidos.EidosSystem.extractFromTextWithDct(EidosSystem.scala:190)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2(ExtractFromDirectory.scala:52)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$2$adapted(ExtractFromDirectory.scala:39)
	at org.clulab.wm.eidos.utils.Closer$.liftedTree1$1(Closer.scala:20)
	at org.clulab.wm.eidos.utils.Closer$.autoClose(Closer.scala:19)
	at org.clulab.wm.eidos.utils.Closer$AutoCloser.autoClose(Closer.scala:60)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1(ExtractFromDirectory.scala:39)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.$anonfun$new$1$adapted(ExtractFromDirectory.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.delayedEndpoint$org$clulab$wm$eidos$apps$ExtractFromDirectory$1(ExtractFromDirectory.scala:36)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$delayedInit$body.apply(ExtractFromDirectory.scala:16)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory$.main(ExtractFromDirectory.scala:16)
	at org.clulab.wm.eidos.apps.ExtractFromDirectory.main(ExtractFromDirectory.scala)
Disconnected from the target VM, address: '127.0.0.1:64438', transport: 'socket'

Process finished with exit code 1
```

**Comment by EgoLaparra** [comment]
This one is caused by a wrong parsing of "in the 21st century". The error in https://github.com/clulab/eidos/issues/664 is caused by "2.1 days in a week". We could avoid these problems catching the exceptions thrown in https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/context/TimeNormFinder.scala#L206-L212.

**Comment by bethard** [comment]
Agreed that we should be catching exceptions in that code and returning `Seq()` when the time expression turns out to be impossible. (We do our best to throw exceptions early, at the time at which a time expression is constructed, rather than when `.start` and `.end` are called, but sometimes it's impossible to know that a time expression is invalid until you try to evaluate it.)
