### ISSUE TITLE
Deduplication error during sbt assembly

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#794]
On the latest master, when running sbt assembly, I am getting an error to do with wm_compositional_metadata.yml. I tried deleting both the implicated jar file in .ivy2 and the target/scala-2.12/classes folder but neither of those solved the issue.

```
[error] 1 error was encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] org/clulab/wm/eidos/english/ontologies/wm_compositional_metadata.yml
[error] /Users/ben/.ivy2/cache/com.github.WorldModelers/Ontologies/jars/Ontologies-master-SNAPSHOT.jar:org/clulab/wm/eidos/english/ontologies/wm_compositional_metadata.yml
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:143)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:68)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:58)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:85)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:244)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (assembly) deduplicate: different file contents found in the following:
[error] org/clulab/wm/eidos/english/ontologies/wm_compositional_metadata.yml
[error] /Users/ben/.ivy2/cache/com.github.WorldModelers/Ontologies/jars/Ontologies-master-SNAPSHOT.jar:org/clulab/wm/eidos/english/ontologies/wm_compositional_metadata.yml

```

**Comment by MihaiSurdeanu** [comment]
@kwalcock: can you please take a look?

**Comment by kwalcock** [comment]
It looks like I forgot something.  It's being addressed with #795.  We've switched over to the WorldModelers/Ontologies version that is on github and don't need the local files, especially if they differ.  It should be ready momentarily.

**Comment by kwalcock** [comment]
@bgyori, can you give it a try?  Also, if you have time can you see #791?  Thanks.

**Comment by bgyori** [comment]
Thanks, #795 solved it!
