### ISSUE TITLE
Error encountered related to time norm

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#796]
While reading a set of text documents, I encountered the error below. I haven't yet isolated the specific document/text to reproduce this which is probably needed to figure out why this happens. I will post more information below as soon as I have more information.
```
Exception in thread "main" scala.MatchError: None (of class scala.None$)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$17(TimeNormFinder.scala:186)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$16(TimeNormFinder.scala:183)
	at org.clulab.wm.eidos.context.TimeNormFinder.$anonfun$find$16$adapted(TimeNormFinder.scala:182)
	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:770)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:769)
	at org.clulab.wm.eidos.context.TimeNormFinder.find(TimeNormFinder.scala:182)
	at org.clulab.wm.eidos.EidosSystem.$anonfun$mkMentions$1(EidosSystem.scala:104)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at org.clulab.wm.eidos.EidosSystem.mkMentions(EidosSystem.scala:103)
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:139)
```

**Comment by MihaiSurdeanu** [comment]
Thanks!

@EgoLaparra, @bethard: can you please look at this?

**Comment by bethard** [comment]
Looks like some time expression is coming back with no character offsets. Once we have at least a document where this is happening, we should be able to debug.

**Comment by bgyori** [comment]
I managed to isolate it to this obscure sentence, which reproduces the error.
```
Proteins were visualised by Western blot analysis as described previously(Treffers et al. 2015)  using primary antibodies mAb-nsp2Eu58-46, mAb-nsp1β Eu22-28 (Li et al., 2014), rabbit polyclonal anti-hnRNP E1 (C-terminal) (PCBP1) (Sigma-Aldrich), mouse monoclonal anti-PCBP2 (M07) (Abgent), rabbit polyclonal anti-human MGC10 (PCBP4) (PromoKine), mouse monoclonal anti-hnRNPK (Abcam), or mouse monoclonal antibody H68.4 against the transferrin receptor (Invitrogen) diluted in PBST containing 1% casein.
```

**Comment by EgoLaparra** [comment]
Maybe a problem with unicode characters again: `mAb-nsp1β`. Let me check it out

**Comment by EgoLaparra** [comment]
We were creating TimeZones without the corresponding charspan. Yeah, there is no time zone in that sentence but, for some reason, the parser believes `al` is. 
I've fixed the error I will release a new version of the parser.

**Comment by kwalcock** [comment]
You probably saw that I added other problematic documents to issues of the timenorm project, but I'll write this just in case.

**Comment by EgoLaparra** [comment]
Yes, I saw it. They were caused by the same reason.

**Comment by kwalcock** [comment]
Please let me know when a new version is released so that I can update Eidos.

**Comment by EgoLaparra** [comment]
@kwalcock, I've just released version 1.0.5

**Comment by kwalcock** [comment]
Thanks!  I'll put it to use.

**Comment by kwalcock** [comment]
Here's output for the four files that didn't run, using default configuration values.  Eidos is still running the unit tests after the update.

[timenorm-update.zip](https://github.com/clulab/eidos/files/4372462/timenorm-update.zip)
