### ISSUE TITLE
Match error in season finder

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#905]
Eidos is having problems processing the attached file.  Remove .txt from the filename.  I'm running ExtractCdrMetaFromDirectory with these arguments: ../corpora/sep2020/input ../corpora/sep2020/output ../corpora/sep2020/time.txt 8.  There's also a VM option: -Xmx20g.  It could be lower.

```
11:56:35.522 [ForkJoinPool-2-worker-1] ERROR o.c.w.e.a.b.ExtractCdrMetaFromDirectory$ - Exception for file ..\corpora\sep2020\input\13e81eea8f1dc02197fe02719631ae94.json
scala.MatchError: season (of class java.lang.String)
	at org.clulab.wm.eidos.context.SeasonFinder.createMention(SeasonFinder.scala:99) ~[classes/:na]
	at org.clulab.wm.eidos.context.SeasonFinder.$anonfun$find$5(SeasonFinder.scala:126) ~[classes/:na]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.map(TraversableLike.scala:234) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.context.SeasonFinder.$anonfun$find$3(SeasonFinder.scala:125) ~[classes/:na]
	at org.clulab.wm.eidos.context.SeasonFinder.$anonfun$find$3$adapted(SeasonFinder.scala:123) ~[classes/:na]
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32) ~[scala-library-2.12.4.jar:na]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241) ~[scala-library-2.12.4.jar:na]
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238) ~[scala-library-2.12.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:191) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.context.SeasonFinder.find(SeasonFinder.scala:123) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.$anonfun$mkMentions$2(EidosSystem.scala:135) ~[classes/:na]
	at org.clulab.wm.eidos.utils.Timer$.time(Timer.scala:77) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.$anonfun$mkMentions$1(EidosSystem.scala:134) ~[classes/:na]
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122) ~[scala-library-2.12.4.jar:na]
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118) ~[scala-library-2.12.4.jar:na]
	at scala.collection.immutable.List.foldLeft(List.scala:86) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.EidosSystem.mkMentions(EidosSystem.scala:133) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:178) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.extractFromDoc(EidosSystem.scala:192) ~[classes/:na]
	at org.clulab.wm.eidos.EidosSystem.extractFromText(EidosSystem.scala:213) ~[classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractCdrMetaFromDirectory$.$anonfun$new$4(ExtractCdrMetaFromDirectory.scala:55) [classes/:na]
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12) ~[scala-library-2.12.4.jar:na]
	at org.clulab.wm.eidos.utils.Timer.time(Timer.scala:13) ~[classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractCdrMetaFromDirectory$.$anonfun$new$3(ExtractCdrMetaFromDirectory.scala:49) [classes/:na]
	at org.clulab.wm.eidos.apps.batch.ExtractCdrMetaFromDirectory$.$anonfun$new$3$adapted(ExtractCdrMetaFromDirectory.scala:44) [classes/:na]
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49) ~[scala-library-2.12.4.jar:na]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library-2.12.4.jar:na]
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145) ~[scala-library-2.12.4.jar:na]
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440) ~[scala-library-2.12.4.jar:na]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) ~[na:1.8.0_181]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_181]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_181]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_181]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_181]
```

[13e81eea8f1dc02197fe02719631ae94.json.txt](https://github.com/clulab/eidos/files/5213131/13e81eea8f1dc02197fe02719631ae94.json.txt)

**Comment by kwalcock** [comment]
@EgoLaparra, if your schedule is booked, let me know and I'll try to get to it sooner.

**Comment by EgoLaparra** [comment]
I see. The match https://github.com/clulab/eidos/blob/b03ca30f3fb073fa6eb504f7c45ca151693a28c9/src/main/scala/org/clulab/wm/eidos/context/SeasonFinder.scala#L99 doesn't capture season mentions at the beginning of the sentence, like in "Season affected the nutritive value...". We need to add a `case _ => None`.

**Comment by EgoLaparra** [comment]
This should be fixed by https://github.com/clulab/eidos/pull/906
