### ISSUE TITLE
TestDoc3, Paragraph 9, edges 2

### ISSUE THREAD

**Issue by kwalcock** [clulab/eidos#978]
Sometimes the tests fails with
```
[info] TestDoc3 Paragraph 9
[info] - should have correct edges 1
[info] - should have correct edges 2 *** FAILED ***
[info]   List("
[info]   Errors:
[info]          Could not find EdgeSpec [persistently well above-average rainfall over the western Ethiopia highlands|+INC(above-average, Quant: persistently, Quant: well)+QUANT(above-average, Quant: persistently, Quant: well)+GEO(Ethiopia)+TIME(the coming weeks)]->(Causal)->[flooding|+TIME(the coming weeks)]
[info]   Mentions:
[info]          #0: TextBoundMention@839043712[likely]
[info]          #1: TextBoundMention@1396362116[persistently well above-average rainfall over the western Ethiopia highlands]
[info]          #2: TextBoundMention@1992834692[reduce]
[info]          #3: TextBoundMention@931963655[good performance of seasonal rainfall]
[info]          #4: TextBoundMention@152069899[above-average]
[info]          #5: TextBoundMention@1792444175[Cropping conditions]
[info]          #6: TextBoundMention@861145747[continued rains]
[info]          #7: TextBoundMention@1951454996[forecast]
[info]          #8: TextBoundMention@308425365[northern areas]
[info]          #9: TextBoundMention@1611219991[Ethiopia]
[info]          #10: TextBoundMention@633241497[well]
[info]          #11: EventMention@348363294[continued rains could also reduce the impact of Fall Armyworm](effect = (TextBoundMention@2094461533[impact of Fall Armyworm]), cause = (TextBoundMention@295704041[continued rains]))
[info]          #12: TextBoundMention@1635076512[persistently]
[info]          #13: TextBoundMention@1668370723[start]
[info]          #14: TextBoundMention@892928291[potential]
[info]          #15: TextBoundMention@161345700[six regions]
[info]          #16: TextBoundMention@50903213[flooding]
[info]          #17: TextBoundMention@1729349166[moderate to heavy]
[info]          #18: TextBoundMention@1897015215[central areas]
[info]          #19: TextBoundMention@1598873520[due]
[info]          #20: EventMention@1338039986[persistently well above-average rainfall over the western Ethiopia highlands could result in flooding](effect = (TextBoundMention@1205583422[flooding]), cause = (TextBoundMention@1396362116[persistently well above-average rainfall over the western Ethiopia highlands]))
[info]          #21: TextBoundMention@1640942643[areas]
[info]          #22: TextBoundMention@360687411[Ethiopia]
[info]          #23: TextBoundMention@2025789495[which will likely contribute to the potential for flooding]
[info]          #24: TextBoundMention@1767070525[infestations]
[info]          #25: TextBoundMention@1205583422[flooding]
[info]          #26: TextBoundMention@278608063[Ethiopia]
[info]          #27: TextBoundMention@1158138308[good]
[info]          #28: TextBoundMention@255700677[favorable]
[info]          #29: TextBoundMention@1169507532[season]
[info]          #30: TextBoundMention@1268635341[areas]
[info]          #31: TextBoundMention@1602525653[Fall]
[info]          #32: TextBoundMention@1554330841[areas]
[info]          #33: TextBoundMention@418413529[rainfall deficits]
[info]          #34: TextBoundMention@2094461533[impact of Fall Armyworm]
[info]          #35: TextBoundMention@145546720[Rainfall]
[info]          #36: TextBoundMention@1798945642[the coming weeks]
[info]          #37: TextBoundMention@1585151339[help]
[info]          #38: TextBoundMention@1455813745[result in]
[info]          #39: TextBoundMention@1577895029[the coming weeks]
[info]          #40: TextBoundMention@674409462[most]
[info]          #41: TextBoundMention@1187000437[have]
[info]          #42: TextBoundMention@393015801[reported]
[info]          #43: EventMention@33349247[Cropping conditions are generally favorable in most western areas and central areas due to good performance of seasonal rainfall](effect = (TextBoundMention@1792444175[Cropping conditions]), cause = (TextBoundMention@931963655[good performance of seasonal rainfall]))
[info]   Found:
[info]          [good performance of seasonal rainfall|+QUANT(good)+POS(good)]->(Causal)->[Cropping conditions|+POS(favorable)+QUANT(favorable)] = #43: EventMention@33349247[Cropping conditions are generally favorable in most western areas and central areas due to good performance of seasonal rainfall](effect = (TextBoundMention@1792444175[Cropping conditions]), cause = (TextBoundMention@931963655[good performance of seasonal rainfall]))
[info]          [good performance of seasonal rainfall|+QUANT(good)+POS(good)] = #3: TextBoundMention@931963655[good performance of seasonal rainfall]
[info]          [persistently well above-average rainfall over the western Ethiopia highlands|+INC(above-average, Quant: persistently, Quant: well)+QUANT(above-average, Quant: persistently, Quant: well)+GEO(Ethiopia)+TIME(the coming weeks)] = #1: TextBoundMention@1396362116[persistently well above-average rainfall over the western Ethiopia highlands]
[info]          [persistently well above-average rainfall over the western Ethiopia highlands|+INC(above-average, Quant: persistently, Quant: well)+QUANT(above-average, Quant: persistently, Quant: well)+GEO(Ethiopia)+TIME(the coming weeks)]->(Causal)->[flooding|+TIME(the coming weeks)] = None
[info]          [flooding|+TIME(the coming weeks)] = #16: TextBoundMention@50903213[flooding]
[info]          [Cropping conditions|+POS(favorable)+QUANT(favorable)] = #5: TextBoundMention@1792444175[Cropping conditions]
[info]   ") was not equal to List() (TestDoc3.scala:323)
```

**Comment by kwalcock** [comment]
At other times it passes.
```
[info] TestDoc3 Paragraph 9
[info] - should have correct edges 1
[info] - should have correct edges 2
[info] - should have correct edges 3
[info] - should have correct edges 4 !!! IGNORED !!!
[info] - should have correct edges 5 !!! IGNORED !!!
```

**Comment by kwalcock** [comment]
At other times it looks like standfordnlp is perhaps not yet ready to run or something.
```
[info] TestDoc3:
[info] org.clulab.wm.eidos.text.english.eval6.TestDoc3 *** ABORTED ***
[info]   edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
[info]   at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:38)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:60)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:43)
[info]   at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:86)
[info]   at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:116)
[info]   at edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:125)
[info]   at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:68)
[info]   at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$5(StanfordCoreNLP.java:523)
[info]   at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$30(StanfordCoreNLP.java:602)
[info]   at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
[info]   ...
[info]   Cause: edu.stanford.nlp.util.MetaClass$ClassCreationException: MetaClass couldn't create public edu.stanford.nlp.time.TimeExpressionExtractorImpl(java.lang.String,java.util.Properties) with args [sutime, {maxAdditionalKnownLCWords=0}]
[info]   at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:237)
[info]   at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
[info]   at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:36)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:60)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:43)
[info]   at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:86)
[info]   at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:116)
[info]   at edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:125)
[info]   at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:68)
[info]   at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$5(StanfordCoreNLP.java:523)
[info]   ...
[info]   Cause: java.lang.reflect.InvocationTargetException:
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:233)
[info]   at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
[info]   at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:36)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:60)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:43)
[info]   at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:86)
[info]   ...
[info]   Cause: java.lang.RuntimeException: Error initializing binder 1
[info]   at edu.stanford.nlp.time.Options.<init>(Options.java:121)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:233)
[info]   at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
[info]   at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:36)
[info]   ...
[info]   Cause: java.lang.IllegalStateException: Cannot create manager class edu.stanford.nlp.time.JollyDayHolidays$MyXMLManager
[info]   at de.jollyday.caching.HolidayManagerValueHandler.instantiateManagerImpl(HolidayManagerValueHandler.java:63)
[info]   at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:41)
[info]   at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:13)
[info]   at de.jollyday.util.Cache.get(Cache.java:51)
[info]   at de.jollyday.HolidayManager.createManager(HolidayManager.java:168)
[info]   at de.jollyday.HolidayManager.getInstance(HolidayManager.java:148)
[info]   at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:57)
[info]   at edu.stanford.nlp.time.Options.<init>(Options.java:119)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
[info]   ...
[info]   Cause: java.lang.ClassCastException: Cannot cast edu.stanford.nlp.time.JollyDayHolidays$MyXMLManager to de.jollyday.HolidayManager
[info]   at java.lang.Class.cast(Class.java:3369)
[info]   at de.jollyday.caching.HolidayManagerValueHandler.instantiateManagerImpl(HolidayManagerValueHandler.java:61)
[info]   at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:41)
[info]   at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:13)
[info]   at de.jollyday.util.Cache.get(Cache.java:51)
[info]   at de.jollyday.HolidayManager.createManager(HolidayManager.java:168)
[info]   at de.jollyday.HolidayManager.getInstance(HolidayManager.java:148)
[info]   at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:57)
[info]   at edu.stanford.nlp.time.Options.<init>(Options.java:119)
[info]   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
[info]   ...
```

**Comment by kwalcock** [comment]
This was hopefully fixed with https://github.com/clulab/eidos/pull/1006.
